### ISSUE TITLE
Confusion about using collections in resolve function

### ISSUE THREAD

**Issue by BearOutThere** [arangodb-foxx/demo-graphql#1]
Hello,
i've been working through the graphql example and can't figure out how actual collections are linked to the type definitions resolve functions.
In the example it says: 
"// In the original graphql-js test fixtures episodes
// are defined using a GraphQL ENUM type. Because we're
// in a database, it makes more sense to define them
// as an object type backed by a collection.
"

and the resolve functions is:

`resolve(episode) {
          // The objects exposed by GraphQL have an "id"
          // field which corresponds to ArangoDB's "_key"
          // property. This mapping isn't strictly necessary
          // but hides the implementation of the data
          // source to make it more consistent with other
          // GraphQL APIs.
          return episode._key;
`

while the collection reference is set by:

`const episodes = applicationContext.collection('episodes');`

so how is 'episode' in resolve function connected to 'episodes' collection reference?

Thanks in advance.

**Comment by BearOutThere** [comment]
Figured out the connection to database collection.  It's happening in the query object.  But still not clear how the AQL queries defined in the types above are called?

**Comment by pluma** [comment]
The collection isn't actually used directly (so the variable is actually not being used at all).

The actual collection in use is `appearsIn`, which is iterated over using an AQL graph query, e.g. (in https://github.com/arangodb-foxx/demo-graphql/blob/master/schema.js#L179):

```
FOR episode IN OUTBOUND ${human._id} ${appearsIn}
SORT episode._key ASC
RETURN episode
```

This iterates over each `_to` vertex of edges in the `appearsIn` collection. The `appearsIn` collection maps `characters` to `episodes`, so the `_to` vertex is an episode.

The `resolve` function you were looking at is the resolve function for an episode's `id` property. The equivalent of a GraphQL `id` is an ArangoDB `_key` (or an `_id` depending on whether you want relative IDs or absolute IDs and how much you want to expose about the underlying collections).
